# Generated by Django 4.0.6 on 2022-07-14 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=50, verbose_name='공원 옵션')),
            ],
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_park', models.CharField(max_length=200, verbose_name='공원명')),
                ('p_addr', models.CharField(max_length=200, verbose_name='공원주소')),
                ('p_zone', models.CharField(max_length=100, verbose_name='지역')),
                ('p_admintel', models.CharField(max_length=20, verbose_name='전화번호')),
                ('main_equip', models.TextField(verbose_name='주요시설')),
                ('template_url', models.URLField(verbose_name='바로가기')),
                ('p_list_content', models.TextField(verbose_name='공원개요')),
                ('p_img', models.CharField(max_length=300, verbose_name='이미지')),
                ('longitude', models.CharField(max_length=50, verbose_name='X좌표')),
                ('latitude', models.CharField(max_length=50, verbose_name='Y좌표')),
                ('check_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='공원 정보 생성시간')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='공원 정보 수정시간')),
            ],
        ),
        migrations.CreateModel(
            name='ParkComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(verbose_name='댓글')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='공원 댓글 생성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='공원 댓글 수정시간')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.park', verbose_name='공원')),
            ],
        ),
    ]
