# Generated by Django 4.0.6 on 2022-08-09 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'park_bookmark',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=50, verbose_name='공원 옵션')),
            ],
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_name', models.CharField(max_length=200, verbose_name='공원명')),
                ('addr', models.CharField(max_length=200, verbose_name='공원주소')),
                ('zone', models.CharField(max_length=100, verbose_name='지역')),
                ('addr_dong', models.CharField(max_length=100, verbose_name='동')),
                ('admintel', models.CharField(max_length=100, verbose_name='전화번호')),
                ('main_equip', models.TextField(blank=True, verbose_name='주요시설')),
                ('template_url', models.URLField(blank=True, verbose_name='바로가기')),
                ('list_content', models.TextField(verbose_name='공원개요')),
                ('image', models.CharField(max_length=300, verbose_name='이미지')),
                ('longitude', models.CharField(blank=True, max_length=50, verbose_name='X좌표')),
                ('latitude', models.CharField(blank=True, max_length=50, verbose_name='Y좌표')),
                ('check_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='공원 정보 생성시간')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='공원 정보 수정시간')),
            ],
        ),
        migrations.CreateModel(
            name='ParkOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.option')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.park')),
            ],
            options={
                'db_table': 'park_park_option',
            },
        ),
        migrations.CreateModel(
            name='ParkComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='댓글')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='공원 댓글 생성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='공원 댓글 수정시간')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.park', verbose_name='공원')),
            ],
        ),
    ]
