# Generated by Django 4.0.6 on 2022-07-14 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('park', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='park',
            name='option',
            field=models.ManyToManyField(related_name='options', to='park.option', verbose_name='공원 옵션'),
        ),
    ]
